### PR TITLE
Fix #293

### LINKED ISSUE #293: [Bug] sqlite deploy error
After configure database as `sqlite`, run `node app.js`
Got the following error.
```
2016-12-22T03:29:36.271Z - error: uncaughtException: Parameter "url" must be a string, not undefined date=Thu Dec 22 2016 11:29:36 GMT+0800 (CST), pid=5938, uid=1000, gid=1000, cwd=/home/apple/hackmd, execPath=/home/apple/.nvm/versions/node/v7.2.1/bin/node, version=v7.2.1, argv=[/home/apple/.nvm/versions/node/v7.2.1/bin/node, /home/apple/hackmd/app.js], rss=63201280, heapTotal=42954752, heapUsed=25305144, external=127817, loadavg=[0.07666015625, 0.3037109375, 0.3427734375], uptime=826, trace=[column=11, file=url.js, function=Url.parse, line=91, method=parse, native=false, column=5, file=url.js, function=Object.urlParse [as parse], line=85, method=urlParse [as parse], native=false, column=24, file=/home/apple/hackmd/node_modules/sequelize/lib/sequelize.js, function=new Sequelize, line=125, method=null, native=false, column=17, file=/home/apple/hackmd/lib/models/index.js, function=, line=19, method=null, native=false, column=32, file=module.js, function=Module._compile, line=571, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=580, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=488, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=447, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=439, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=498, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=14, file=/home/apple/hackmd/lib/auth.js, function=, line=16, method=null, native=false, column=32, file=module.js, function=Module._compile, line=571, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=580, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=488, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=447, method=null, native=false], stack=[TypeError: Parameter "url" must be a string, not undefined,     at Url.parse (url.js:91:11),     at Object.urlParse [as parse] (url.js:85:5),     at new Sequelize (/home/apple/hackmd/node_modules/sequelize/lib/sequelize.js:125:24),     at Object.<anonymous> (/home/apple/hackmd/lib/models/index.js:19:17),     at Module._compile (module.js:571:32),     at Object.Module._extensions..js (module.js:580:10),     at Module.load (module.js:488:32),     at tryModuleLoad (module.js:447:12),     at Function.Module._load (module.js:439:3),     at Module.require (module.js:498:17),     at require (internal/module.js:20:19),     at Object.<anonymous> (/home/apple/hackmd/lib/auth.js:16:14),     at Module._compile (module.js:571:32),     at Object.Module._extensions..js (module.js:580:10),     at Module.load (module.js:488:32),     at tryModuleLoad (module.js:447:12)]
```
This bug is caused by sequelize initialize error
https://github.com/hackmdio/hackmd/blob/master/lib/models/index.js#L19

```nodejs
else
    sequelize = new Sequelize(dbconfig.database, dbconfig);
```
null value of username and password should also be parsed into Sequelize
```nodejs
else
    sequelize = new Sequelize(dbconfig.database, dbconfig.username, dbconfig.password, dbconfig);
```
Like the following example config file.
https://github.com/sequelize/express-example/blob/master/models/index.js

### PR DESCRIPTION
**Pull request by bananaappletw**
Fix #293
This pull request follow this example config file.
https://github.com/sequelize/express-example/blob/master/models/index.js

### CODE REVIEW

File: lib/models/index.js [hunk 1]
```diff
@@ -13,10 +13,11 @@ var dbconfig = config.db;
 dbconfig.logging = config.debug ? logger.info : false;
 
 var sequelize = null;
-if (dbconfig.hasOwnProperty('username') || dbconfig.hasOwnProperty('password'))
-    sequelize = new Sequelize(dbconfig.database, dbconfig.username, dbconfig.password, dbconfig);
+
+if (process.env.DATABASE_URL)
```
Comment (Yukaii) [inline lib/models/index.js]: Also `bin/heroku:22-33` will be the following for now.
 
```json
{
  "production": {
  }
}
```

Comment (bananaappletw) [inline lib/models/index.js]: @Yukaii 
I changed it, appended to the another commit.
Thanks for the review.

File: lib/models/index.js [hunk 2]
```diff
@@ -13,10 +13,11 @@ var dbconfig = config.db;
...
+    sequelize = new Sequelize(process.env.DATABASE_URL, dbconfig.username, dbconfig.password, dbconfig);
```
Comment (Yukaii) [inline lib/models/index.js]: @jackycute Or even simpler, write this for heroku specific case?

```javascript
sequelize = new Sequelize(process.env.DATABASE_URL);
```

Comment (jackycute) [inline lib/models/index.js]: I think yes. That's better.

Comment (SISheogorath) [inline lib/models/index.js]: For heruko this is may better but you don't pass useful parameters to object constructor like `pool` configs etc. The last parameter is very powerful and shouldn't removed even if it's possible. On one hand for backwards compatibility reasons (may someone uses it) on the other hand to may optimize database handling later.

Comment (jackycute) [inline lib/models/index.js]: @SISheogorath This fix is borrowed from the official sequelize example https://github.com/sequelize/express-example/blob/master/models/index.js
And it's ok to pass undefined parameter to the constructor according to their document http://sequelize.readthedocs.io/en/latest/api/sequelize/

I believe this will remain backwards compatibility because usually you'll fall into the full constructor.

**Comment by SISheogorath** [comment]
I just reviewed the whole db config handling and would change it by move the configs made for this PR addressed in https://github.com/hackmdio/hackmd/blob/master/lib/config.js instead of the models. This centralizes configs a bit more.

**Comment by jackycute** [comment]
Thanks @bananaappletw @Yukaii @SISheogorath
